services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # RelativeDate

    ## Format

    Denbad\RelativeDate\Strategy\RelativeDateStrategy:
      tags:
          - { name: 'date_formatter.strategy' }

    Denbad\RelativeDate\Strategy\RelativeDateTimeStrategy:
      tags:
          - { name: 'date_formatter.strategy' }

    ## Middleware

    Denbad\RelativeDate\Middleware\CachesMiddleware:
      tags:
          - { name: 'date_formatter.middleware', priority: 110 }

    Denbad\RelativeDate\Middleware\ConvertsToRelativeMiddleware:
      arguments: [!tagged 'date_formatter.strategy']
      tags:
          - { name: 'date_formatter.middleware', priority: 100 }

    Denbad\RelativeDate\Middleware\TranslatesMiddleware:
      tags:
          - { name: 'date_formatter.middleware', priority: 90 }

    Denbad\RelativeDate\Middleware\CapitalizesMiddleware:
      tags:
        - { name: 'date_formatter.middleware', priority: 80 }

    ## Formatter

    Denbad\RelativeDate\Formatter\CompositeFormatter:
        arguments: [!tagged 'date_formatter.middleware']

    # RelativeDateSymfonyBridge

    ## Middleware Translator

    Denbad\RelativeDateSymfonyBridge\Middleware\TranslatorAdapter: ~